base_url = "https://zola-divpattern.netlify.com"
compile_sass = true
title = "divpattern theme"
description = "A clean blogging theme"
generate_feed = true

[extra]
divpattern_sticky = true
divpattern_reverse = false
divpattern_theme = ""
divpattern_links = [
    {url = "https://google.com", name = "About"},
]
