name = "divpattern"
description = "A simple blog theme"
license = "MIT"
homepage = "https://github.com/highb/divpattern"
min_version = "0.11.0"
demo = "https://divpattern.com"

[extra]
divpattern_sticky = true
divpattern_reverse = false
divpattern_theme = ""
divpattern_links = [
]

[author]
name = "Brandon High"
homepage = "https://bmh.io"

[original]
author =  "mdo (Ported to zola by Vincent Prouillet)"
homepage = "http://markdotto.com/"
repo = "https://www.github.com/mdo/divpattern"
